try {
    var a = 5;
    var b = 6;
    console.log(a+c)
} catch(err) {
    console.log('There was an error')
}

//catch block that the try block catches so your code will continue to run
// a+b is not defined so an error will produce
//benefit of try/catch it will not stop javascript execution.
//try catch will not work if there is a syntax error within javascript

//Null = represents intentional abscence of object value

//RECURSION = When a function calls itself again